repos:
  - repo: https://github.com/pypa/pip-audit
    rev: v2.8.0
    hooks:
      - id: pip-audit
        args: [--vulnerability-service, "pypi", --cache-dir, ".pip_audit_cache"]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.5
    hooks:
      - id: ruff  # linter
        args: [--fix]
      - id: ruff-format  # formatter
